### ISSUE TITLE
objectid kills payload for me

### ISSUE THREAD

**Issue by biancode** [Chris1234567899/node-red-contrib-objectid#3]
Hi Chris,

I see the option to select a property to fill in your code, but it doesn't work in my case.

![image](https://user-images.githubusercontent.com/4369867/30002403-e7c57114-90a8-11e7-9d7d-bb7442a8a9a6.png)

Did you push it via NPM? Ideas?

A better default could be some like "msg.payload._id" instead of filling payload by default

Happy coding!
Klaus

**Comment by vicary** [comment]
My PR was merged once but never pushed to npm :(

**Comment by biancode** [comment]
should be fixed in v0.6.1
